### ISSUE TITLE
"Node 'admin' does not exist in this deployment" error when trying to establish an SSH tunnel

### ISSUE THREAD

**Issue by LenzGr** [rjfd/sesdev#25]
This happens in a current git checkout (rev f6f2697cecef5ef822b07154685a89c0d93af6e2):

After creating a new cluster using `sesdev create nautilus --single-node nautilus-singlenode`, establishing an SSH tunnel using the command displayed in the end of the output fails:

```
$ sesdev tunnel nautilus-singlenode dashboard
Opening tunnel to service 'dashboard'...
Node 'admin' does not exist in this deployment
```

The node is actually called `node1` in this setup.

**Comment by LenzGr** [comment]
Adding some debug output reveals that the node name `admin` seems to be hardcoded somewhere, still investigating:
```
$ sesdev tunnel nautilus-singlenode dashboard      
Opening tunnel to service 'dashboard' on node 'admin'...
Node 'admin' does not exist in this deployment
$ sesdev tunnel --node node1 nautilus-singlenode dashboard
Opening tunnel to service 'dashboard' on node 'node1'...
Node 'admin' does not exist in this deployment
```

**Comment by LenzGr** [comment]
The `ssh` commands fails with a similar issue:
```
$ sesdev ssh nautilus-singlenode
Node 'admin' does not exist in this deployment
```

**Comment by LenzGr** [comment]
Here's a log when running `sesdev --debug --log-file sesdev.log tunnel --node node1 nautilus-singlenode dashboard`:
```
2019-12-06 14:46:01,792 [INFO] [seslib.tools] Running sync command (/home/lenz/.sesdev/nautilus-singlenode): ['vagrant', 'status']
2019-12-06 14:46:03,198 [ERROR] [sesdev] Node 'admin' does not exist in this deployment
Traceback (most recent call last):
  File "/home/lenz/work/sesdev/sesdev/__init__.py", line 16, in sesdev_main
    cli(prog_name='sesdev')
  File "/home/lenz/virtualenv/sesdev/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lenz/virtualenv/sesdev/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lenz/virtualenv/sesdev/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lenz/virtualenv/sesdev/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lenz/virtualenv/sesdev/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lenz/work/sesdev/sesdev/__init__.py", line 527, in tunnel
    dep.start_port_forwarding(service, node, remote_port, local_port, local_address)
  File "/home/lenz/work/sesdev/seslib/__init__.py", line 771, in start_port_forwarding
    ssh_cmd = self._ssh_cmd('admin')
  File "/home/lenz/work/sesdev/seslib/__init__.py", line 707, in _ssh_cmd
    raise NodeDoesNotExist(name)
seslib.exceptions.NodeDoesNotExist: Node 'admin' does not exist in this deployment
```

**Comment by LenzGr** [comment]
The `roles` output of `sesdev show nautilus-singlenode` looks somewhat weird, not sure if that's related:
``` 
Deployment VMs:
  -- node1:
     - status:           running
     - OS:               leap-15.1
     - ses_version:      nautilus
     - roles:            ['mds', 'igw', 'mgr', 'rgw', 'ganesha ]', 'storage', 'prometheus', '[   admin', 'grafana', 'mon']
     - fqdn:             node1.nautilus-singlenode.com
     - public_address:   10.20.179.201
     - cpus:             2
     - ram:              4G
     - storage_disks:    3
       - /dev/vdb        8G
       - /dev/vdc        8G
       - /dev/vdd        8G
     - repo_priority:    True
```
